import { Geist, Geist_Mono } from "next/font/google";
import Header from "./components/Header";
import "./globals.css";
import HeroSection from "./components/HeroSection";
import AboutSection from "./components/AboutSection";
import FooterSection from "./components/FooterSection";
import ExperienceSection from "./components/ExperienceSection";
import ServicesSection from "./components/ServicesSection";
import FAQSection from "./components/FAQSection";
import ContactForm from "./components/ContactForm";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header/>
        <HeroSection />
        <ExperienceSection />
        <ServicesSection />
        <AboutSection />
        <FAQSection />
        <ContactForm />
        <FooterSection />
        {children}
      </body>
    </html>
  );
}
